# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow1.ui'
#
# Created: Sun May 09 19:35:52 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 672)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(390, 10, 585, 437))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mplwidget.setPalette(palette)
        self.mplwidget.setObjectName("mplwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(15, 160, 361, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.BinButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.BinButton.setObjectName("BinButton")
        self.gridLayout_2.addWidget(self.BinButton, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.FFTlim = QtGui.QSpinBox(self.gridLayoutWidget)
        self.FFTlim.setMaximum(999)
        self.FFTlim.setProperty("value", QtCore.QVariant(10))
        self.FFTlim.setObjectName("FFTlim")
        self.gridLayout_2.addWidget(self.FFTlim, 6, 1, 1, 1)
        self.FFTtype = QtGui.QComboBox(self.gridLayoutWidget)
        self.FFTtype.setEditable(False)
        self.FFTtype.setMaxVisibleItems(2)
        self.FFTtype.setObjectName("FFTtype")
        self.FFTtype.addItem(QtCore.QString())
        self.FFTtype.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.FFTtype, 7, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 9, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 10, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 11, 0, 1, 1)
        self.WindowLength = QtGui.QSpinBox(self.gridLayoutWidget)
        self.WindowLength.setMaximum(9999)
        self.WindowLength.setProperty("value", QtCore.QVariant(11))
        self.WindowLength.setObjectName("WindowLength")
        self.gridLayout_2.addWidget(self.WindowLength, 10, 1, 1, 1)
        self.WindowType = QtGui.QComboBox(self.gridLayoutWidget)
        self.WindowType.setObjectName("WindowType")
        self.WindowType.addItem(QtCore.QString())
        self.WindowType.addItem(QtCore.QString())
        self.WindowType.addItem(QtCore.QString())
        self.WindowType.addItem(QtCore.QString())
        self.WindowType.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.WindowType, 11, 1, 1, 1)
        self.FFTbutton = QtGui.QPushButton(self.gridLayoutWidget)
        self.FFTbutton.setObjectName("FFTbutton")
        self.gridLayout_2.addWidget(self.FFTbutton, 8, 1, 1, 1)
        self.WindowButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.WindowButton.setObjectName("WindowButton")
        self.gridLayout_2.addWidget(self.WindowButton, 12, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.BinNumber = QtGui.QSpinBox(self.gridLayoutWidget)
        self.BinNumber.setMinimum(1)
        self.BinNumber.setMaximum(9999)
        self.BinNumber.setObjectName("BinNumber")
        self.gridLayout_2.addWidget(self.BinNumber, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(15, 480, 361, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 2)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 2)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.PlotPeaks = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.PlotPeaks.setObjectName("PlotPeaks")
        self.gridLayout_3.addWidget(self.PlotPeaks, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 2)
        self.AutomatedAnalysis = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.AutomatedAnalysis.setObjectName("AutomatedAnalysis")
        self.gridLayout_3.addWidget(self.AutomatedAnalysis, 5, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.FindPeaks = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.FindPeaks.setObjectName("FindPeaks")
        self.gridLayout_3.addWidget(self.FindPeaks, 3, 0, 1, 1)
        self.PeakFitCutoff = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.PeakFitCutoff.setMinimum(0.1)
        self.PeakFitCutoff.setSingleStep(0.1)
        self.PeakFitCutoff.setProperty("value", QtCore.QVariant(2.0))
        self.PeakFitCutoff.setObjectName("PeakFitCutoff")
        self.gridLayout_3.addWidget(self.PeakFitCutoff, 2, 1, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 10, 361, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonOpen = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.gridLayout.addWidget(self.pushButtonOpen, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditCurrentFile = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditCurrentFile.setReadOnly(True)
        self.lineEditCurrentFile.setObjectName("lineEditCurrentFile")
        self.gridLayout.addWidget(self.lineEditCurrentFile, 1, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEditFileStart = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditFileStart.setReadOnly(True)
        self.lineEditFileStart.setObjectName("lineEditFileStart")
        self.gridLayout.addWidget(self.lineEditFileStart, 2, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEditFileEnd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditFileEnd.setReadOnly(True)
        self.lineEditFileEnd.setObjectName("lineEditFileEnd")
        self.gridLayout.addWidget(self.lineEditFileEnd, 3, 1, 1, 2)
        self.pushButtonPlotRaw = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonPlotRaw.setObjectName("pushButtonPlotRaw")
        self.gridLayout.addWidget(self.pushButtonPlotRaw, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.pushButtonAbout = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonAbout.setObjectName("pushButtonAbout")
        self.gridLayout.addWidget(self.pushButtonAbout, 0, 3, 1, 1)
        self.LengthofFile = QtGui.QLineEdit(self.layoutWidget)
        self.LengthofFile.setObjectName("LengthofFile")
        self.gridLayout.addWidget(self.LengthofFile, 4, 1, 1, 1)
        self.NumberofSamples = QtGui.QLineEdit(self.layoutWidget)
        self.NumberofSamples.setObjectName("NumberofSamples")
        self.gridLayout.addWidget(self.NumberofSamples, 4, 3, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 440, 586, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_2 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.ExternalPlot = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.ExternalPlot.setObjectName("ExternalPlot")
        self.horizontalLayout.addWidget(self.ExternalPlot)
        self.CustomPlot = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.CustomPlot.setObjectName("CustomPlot")
        self.horizontalLayout.addWidget(self.CustomPlot)
        self.line = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.ClearButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout.addWidget(self.ClearButton)
        self.SaveGraphButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.SaveGraphButton.setObjectName("SaveGraphButton")
        self.horizontalLayout.addWidget(self.SaveGraphButton)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(390, 480, 586, 171))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 3)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 4)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 3, 0, 1, 1)
        self.SavetoFile = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.SavetoFile.setObjectName("SavetoFile")
        self.gridLayout_4.addWidget(self.SavetoFile, 2, 3, 1, 1)
        self.PartSave = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.PartSave.setObjectName("PartSave")
        self.gridLayout_4.addWidget(self.PartSave, 4, 3, 1, 1)
        self.StartTime = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.StartTime.setObjectName("StartTime")
        self.gridLayout_4.addWidget(self.StartTime, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 2, 1, 1)
        self.EndTime = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.EndTime.setObjectName("EndTime")
        self.gridLayout_4.addWidget(self.EndTime, 3, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 5, 0, 1, 3)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 0, 1, 4)
        self.SavePeaks = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.SavePeaks.setObjectName("SavePeaks")
        self.gridLayout_4.addWidget(self.SavePeaks, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PriMaRy Jove Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Smoothing by Binning:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Length of one bin (seconds):", None, QtGui.QApplication.UnicodeUTF8))
        self.BinButton.setText(QtGui.QApplication.translate("MainWindow", "Bin Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Band Pass Filter Smoothing:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Filter Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Filter Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.FFTtype.setItemText(0, QtGui.QApplication.translate("MainWindow", "low", None, QtGui.QApplication.UnicodeUTF8))
        self.FFTtype.setItemText(1, QtGui.QApplication.translate("MainWindow", "high", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Window Function Smoothing:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Window Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Window Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowType.setItemText(0, QtGui.QApplication.translate("MainWindow", "hanning", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowType.setItemText(1, QtGui.QApplication.translate("MainWindow", "flat", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowType.setItemText(2, QtGui.QApplication.translate("MainWindow", "hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowType.setItemText(3, QtGui.QApplication.translate("MainWindow", "bartlett", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowType.setItemText(4, QtGui.QApplication.translate("MainWindow", "blackman", None, QtGui.QApplication.UnicodeUTF8))
        self.FFTbutton.setText(QtGui.QApplication.translate("MainWindow", "Band Pass Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.WindowButton.setText(QtGui.QApplication.translate("MainWindow", "Window Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">Data Smoothing and Noise Reduction</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">Peak Finding and Automated Analysis</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Peak Fitting on Current Data:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Standard Deviation cut off:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotPeaks.setText(QtGui.QApplication.translate("MainWindow", "Plot Found Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Automated File Analysis:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.AutomatedAnalysis.setText(QtGui.QApplication.translate("MainWindow", "Automated Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Auto Smooth and find time of possible events:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.FindPeaks.setText(QtGui.QApplication.translate("MainWindow", "Find Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "File Open:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">File Starts:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">File Ends:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPlotRaw.setText(QtGui.QApplication.translate("MainWindow", "Plot Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Length of File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Number of Samples:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.ExternalPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot in New Window", None, QtGui.QApplication.UnicodeUTF8))
        self.CustomPlot.setText(QtGui.QApplication.translate("MainWindow", "Custom Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Last Data", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveGraphButton.setText(QtGui.QApplication.translate("MainWindow", "Save Current Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Save Current Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">Saving Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Start Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.SavetoFile.setText(QtGui.QApplication.translate("MainWindow", "Save to File", None, QtGui.QApplication.UnicodeUTF8))
        self.PartSave.setText(QtGui.QApplication.translate("MainWindow", "Save Part to File", None, QtGui.QApplication.UnicodeUTF8))
        self.StartTime.setText(QtGui.QApplication.translate("MainWindow", "HH:MM:SS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "End Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.EndTime.setText(QtGui.QApplication.translate("MainWindow", "HH:MM:SS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Save peak fitting parameters:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Save the Current saved data array:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.SavePeaks.setText(QtGui.QApplication.translate("MainWindow", "Save Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
